name: "publish"

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: https://registry.npm.org          
      - name: npm-publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  
