name: "test"

on:
  push:
    branches:
      - develop

jobs:
  testing:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v2
        with:
            node-version: 10
      - name: test
        run: npm ci
        run: npm run test        
